# Use root/example as user/password credentials
version: '3.9'

services:
    # Use root/example as user/password credentials
    db:
        image: mysql:8.0.33
        # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
        # (this is just an example, not intended to be a production configuration)
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_DATABASE: 'db'
            MYSQL_ROOT_PASSWORD: example
            MYSQL_ROOT_HOST: '%'
        ports:
            - '127.0.0.1:13306:3306'
        expose:
            - '3306'

    localstack:
        container_name: localstack
        image: docker.io/localstack/localstack
        ports:
            - '127.0.0.1:4566:4566'
            - '127.0.0.1:4571:4571'
        environment:
            - SERVICES=s3
            - DEFAULT_REGION=eu-west-1
        tmpfs:
            - /tmp/localstack:exec,mode=600
