services:
    # Use root/example as user/password credentials
    db:
        container_name: apistatox.mysql
        image: mysql:8.0.33
        # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
        # (this is just an example, not intended to be a production configuration)
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_DATABASE: 'db'
            MYSQL_ROOT_PASSWORD: example
            MYSQL_ROOT_HOST: '%'
        ports:
            - '127.0.0.1:23306:3306'
        # Store the data in memory and not on disk (drastically improves tests run time)
        tmpfs:
            - /var/lib/mysql:rw

    localstack:
        container_name: apistatox.localstack
        image: docker.io/localstack/localstack
        ports:
            - '127.0.0.1:24566:4566'
            - '127.0.0.1:24571:4571'
        environment:
            - SERVICES=s3
        tmpfs:
            - /tmp/localstack:exec,mode=600

    elk:
        container_name: apistatox.elk
        image: docker.elastic.co/elasticsearch/elasticsearch:8.15.2
        tmpfs:
            - /usr/share/elasticsearch/data:rw
        ports:
            - '127.0.0.1:29200:9200'
        environment:
            - node.name=es01
            - cluster.name=apistatox
            - discovery.type=single-node
            - ELASTIC_PASSWORD=foo
            - bootstrap.memory_lock=true
            - xpack.ml.enabled=false
            - xpack.security.enabled=false
            - xpack.security.http.ssl.enabled=false
            - xpack.security.transport.ssl.enabled=false
            - xpack.license.self_generated.type=basic
        mem_limit: 1g

    # Uncomment if a Kibana is needed to inspect local ELK
    # Use http://localhost:25601, no password required
    # The data view must be recreated manually until I implement automatically recreating it
    # kibana:
    #     container_name: apistatox.kibana
    #     restart: unless-stopped
    #     image: docker.elastic.co/kibana/kibana:{CHANGEME: USE SAME VERSION AS ELK}
    #     tmpfs:
    #         - /usr/share/kibana/data
    #     ports:
    #         - '127.0.0.1:25601:5601'
    #     environment:
    #         - SERVERNAME=kibana
    #         - ELASTICSEARCH_HOSTS=http://apistatox.elk:9200
    #         - ELASTICSEARCH_USERNAME=kibana_system
    #         - ELASTICSEARCH_PASSWORD=foo
